// Auto-generated by scripts/generate-route-types.js
export type AppRouteName =
  | 'home'
  | 'learning-hub'
  | 'vocabulary'
  | 'exam'
  | 'games-hub'
  | 'game-reaction'
  | 'game-number-guess'
  | 'game-memory'
  | 'game-pop-blast'
